name: Cypress Tests

on:
  push:
    branches:
      - main
      - exercicios/modulo-4
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: npx cypress run

      - name: Preparar relatório para GitHub Pages
        if: always()
        run: |
          mkdir -p public
          cp cypress/reports/*.html public/index.html

      - name: Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public