name: Cypress Tests

on:
  push:
    branches:
      - main
      - exercicios/modulo-4
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress com Mochawesome
        run: |
          npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=true,html=true,json=true

      - name: Verificar arquivos gerados
        run: ls -R

      - name: Preparar relatório
        run: |
          mkdir public
          cp mochawesome-report/mochawesome.html public/index.html

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public